services:
  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      opensearch:
        condition: service_started
    networks:
      - opensearch-net
    environment:
      - FLASK_ENV=development

networks:
  opensearch-net:

volumes:
  opensearch-data: